CREATE TABLE `user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_type` tinyint(4) NOT NULL DEFAULT '100' COMMENT '游客注册=10 正常注册=100',
  `status` tinyint(4) NOT NULL DEFAULT '100' COMMENT '100=正常登录 0=被管理员拒绝',
  `login_account` varchar(128) COLLATE utf8_unicode_ci NOT NULL COMMENT '登录名',
  `login_pass` varchar(64) COLLATE utf8_unicode_ci NOT NULL COMMENT '登录密码',
  `mail` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '绑定邮箱',
  `mail_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0=未绑定 100=已绑定',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_ip` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '创建ip',
  `create_plat` tinyint(4) NOT NULL DEFAULT '0' COMMENT '10=ios,20=android',
  `create_channel` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时的渠道ID',
  `create_udid` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '注册时的udid',
  `create_vcode` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '注册时的vcode',
  `create_devicetype` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '注册时的devicetype',
  `last_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最后登录时间',
  `last_ip` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '最后登录ip',
  `last_plat` tinyint(4) NOT NULL DEFAULT '0' COMMENT '10=ios,20=android',
  `last_channel` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最后登录时的渠道号',
  `last_udid` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '最后登录时的udid',
  `last_vcode` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '最后登录时的vcode',
  `last_devicetype` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '最后登录时的devicetype',
  `count_login` int(11) NOT NULL DEFAULT '0' COMMENT '登录次数',
  `token` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `login_name` (`login_account`),
  KEY `login_pass` (`login_pass`),
  KEY `create_time` (`create_time`),
  KEY `login_time` (`last_time`),
  KEY `count_login` (`count_login`),
  KEY `token` (`token`),
  KEY `last_udid` (`last_udid`),
  KEY `create_udid` (`create_udid`),
  KEY `create_vcode` (`create_vcode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='玩家表'